### ISSUE TITLE
Unexpected behavior: Unhelpful error messages when requesting JSON for levels not supported by the backend

### ISSUE THREAD

**Issue by parkero** [GregoryCannon/TetrisTrainer#31]
### Recreation: 
1. Set level as 15 at beginning screen
2. Start the game
3. Click "Calculate"

### Expected: 
The game should let one know the level they have chosen is not supported by the back end.

### Actual:
The game returns a cryptic error message

### Potential Fix: 
A helpful error message exists in the json request response, displayed below.
If the json parse fails, then the error could be set to the plain text of the response.

<img src="https://user-images.githubusercontent.com/7399144/182715870-0613b2ac-228f-4ab1-ab0d-d860b7fbf597.png" width="400">

**Comment by GregoryCannon** [comment]
Fixed with the latest commit!
https://github.com/GregoryCannon/TetrisTrainer/commit/471e656e0020f737ce7a348ea2ada1ec37c02554

**Comment by GregoryCannon** [comment]
(Now all lower-level requests will request the 18 placement)
