### ISSUE TITLE
Arrow keys scroll the web page

### ISSUE THREAD

**Issue by User670** [GregoryCannon/TetrisTrainer#32]
When a game control key is an arrow key, pressing the key will scroll the webpage too.

For now I can zoom out the web page so that there is no scrolling possible, but wonder if there can be improvement in the code that can help with that.

**Comment by GregoryCannon** [comment]
Long overdue, but fixed with the following commit!
https://github.com/GregoryCannon/TetrisTrainer/commit/1c4816b6a908ff201c855861f87b24afc0e4837c

**Comment by User670** [comment]
Hmm interesting that you only made soft drop prevent default.

tbh in *practice* I don't think anyone will have an issue with current implementation, but in *theory* someone could have the down arrow mapped for some other action and that will scroll the page down.
